version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: rabbiturlshortener_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rabbiturlshortener
      - MYSQL_USER=rabbiturlshortener
      - MYSQL_PASSWORD=rabbiturlshortener

    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rabbiturlshortener_phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always

  nginx:
    image: nginx:1.20
    container_name: rabbiturlshortener_nginx
    volumes:
      - ../api/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${API_PORT}:80"
    restart: always

  php:
    build:
      context: ./php
    image: rabbiturlshortener/php # names builded image
    container_name: rabbiturlshortener_php
    volumes:
      - ../api/:/var/www/html
    restart: always
